version: '2'
services:
  wakemon:
    build: ./
    # volumes:
      # DEV PURPOSE ONLY
      # - $WAKEMON_SRC:/src
    environment:
      - VIRTUAL_HOST=$WAKEMON_HOST
      - VIRTUAL_PORT=3000
    ports:
      - $WAKEMON_PORT:3000
  reverse-proxy:
    image: jwilder/nginx-proxy
    ports:
      - $HTTP_PORT:80/tcp
      - $HTTPS_PORT:443/tcp
    volumes:
      - $DOCKER_SOCK:/tmp/docker.sock:ro
